### ISSUE TITLE
No documentation for import a dataset

### ISSUE THREAD

**Issue by ntouati** [bapaumet/Gflowiz#58]
Hello,
Is it normal that there is no content in the page "[Import dataset](http://arabesque.ifsttar.fr/docs/import-a-dataset.html)" ?
Thanks,

**Comment by fbahoken** [comment]
Hello Ntouati,

It's better to connect to the latest version of the documentation, available at the following address: 
[arabesque-doc](https://gflowiz.github.io/arabesque-doc/)

(it will be available on the home page at the next update)
